### ISSUE TITLE
Support for Jellyfin 10.8.x?

### ISSUE THREAD

**Issue by Pascal51882** [jellyfin/jellyfin-plugin-simkl#18] opened 2022-06-23 17:22 UTC
I can not downgrade because I get login errors in to my server at 10.7.X.
Is there any update planned?

**Comment by crobibero** [comment] 2022-07-05 08:00
Assuming duplicate of https://github.com/jellyfin/jellyfin-plugin-simkl/issues/9

**Closed by crobibero** 2022-07-05 08:00 UTC
